# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-19 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestDayParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('meeting_location', models.CharField(choices=[('\uc6d0\ud1b5', 'Freshman'), ('\uc11c\ud654', 'Sophomore')], default='\uc6d0\ud1b5', max_length=2)),
                ('startDay', models.DateField(help_text='Day of the event', verbose_name='Day of the event')),
                ('content', models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Textual Notes')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ArticleReview',
        ),
    ]
