# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-19 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_auto_20180919_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restdayparty',
            name='meeting_location',
            field=models.CharField(choices=[('\uc6d0\ud1b5', '\uc6d0\ud1b5'), ('\uc11c\ud654', '\uc11c\ud654')], default='\uc6d0\ud1b5', max_length=2),
        ),
    ]
