# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-19 07:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test1', '0003_auto_20180919_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcipate_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='account')),
                ('party_pk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test1.RestDayParty', verbose_name='pk')),
            ],
        ),
    ]
