# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-19 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_parcipate_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcipate_list',
            old_name='party_pk',
            new_name='party',
        ),
    ]
