# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-19 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0005_auto_20180919_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcipate_list',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test1.RestDayParty', verbose_name='partt'),
        ),
    ]
