# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-19 07:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0007_auto_20180919_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcipate_list',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='account'),
        ),
        migrations.AlterField(
            model_name='parcipate_list',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.RestDayParty', verbose_name='party'),
        ),
    ]
