# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-25 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0009_auto_20180925_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcipate_list',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='parcipate_list',
            name='party',
        ),
        migrations.DeleteModel(
            name='Parcipate_list',
        ),
    ]
