# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-26 07:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_location', models.CharField(choices=[('\uc6d0\ud1b5', '\uc6d0\ud1b5'), ('\uc11c\ud654', '\uc11c\ud654')], default='\uc11c\ud654', max_length=2)),
                ('arrival_location', models.CharField(choices=[('\uc6d0\ud1b5', '\uc6d0\ud1b5'), ('\uc11c\ud654', '\uc11c\ud654')], default='\uc6d0\ud1b5', max_length=2)),
                ('way', models.CharField(choices=[('taxi', 'taxi'), ('carpool', 'carpool')], default='taxi', max_length=2)),
                ('departure_date', models.DateField(help_text='\ucd9c\ubc1c\ub0a0\uc9dc', verbose_name='\ucd9c\ubc1c\ub0a0\uc9dc')),
                ('content', models.TextField(blank=True, help_text='\uac8c\uc2dc\ubb3c \ub0b4\uc6a9', null=True, verbose_name='\uac8c\uc2dc\ubb3c \ub0b4\uc6a9')),
                ('published_date', models.DateTimeField(verbose_name='date published')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='resttest.Event'),
        ),
    ]
