# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-26 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resttest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='way',
            field=models.CharField(choices=[('taxi', 'taxi'), ('carpool', 'carpool')], default='taxi', max_length=4),
        ),
    ]
