# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-26 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resttest', '0003_auto_20180926_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='published_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
